[2024-09-24T17:41:19.351+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T17:41:19.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_classifier_dag.get_data manual__2024-09-24T17:41:15.640038+00:00 [queued]>
[2024-09-24T17:41:19.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_classifier_dag.get_data manual__2024-09-24T17:41:15.640038+00:00 [queued]>
[2024-09-24T17:41:19.376+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T17:41:19.388+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-09-24 17:41:15.640038+00:00
[2024-09-24T17:41:19.395+0000] {standard_task_runner.py:64} INFO - Started process 28555 to run task
[2024-09-24T17:41:19.398+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_classifier_dag', 'get_data', 'manual__2024-09-24T17:41:15.640038+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpa1kgua3o']
[2024-09-24T17:41:19.401+0000] {standard_task_runner.py:91} INFO - Job 372: Subtask get_data
[2024-09-24T17:41:19.445+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_classifier_dag.get_data manual__2024-09-24T17:41:15.640038+00:00 [running]> on host 82997fc6deb7
[2024-09-24T17:41:19.518+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='random_forest_classifier_dag' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T17:41:15.640038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T17:41:15.640038+00:00'
[2024-09-24T17:41:19.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T17:41:19.529+0000] {hw1-checkpoint.py:90} INFO - Get data...
[2024-09-24T17:41:19.929+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T17:41:19.931+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T17:41:20.380+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T17:41:20.382+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow/dags/.ipynb_checkpoints/hw1-checkpoint.py", line 101, in get_data
    s3_save_file(kwargs['model_name'], 'dataset', data)
  File "/opt/airflow/dags/airflow/dags/.ipynb_checkpoints/hw1-checkpoint.py", line 72, in s3_save_file
    s3_hook.load_file_obj(file_obj=buffer.getvalue(), key=f"AlexTrigolos/{model_name}/datasets/{file_name}.pkl", bucket_name=BUCKET, replace=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1234, in load_file_obj
    self._upload_file_obj(file_obj, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1255, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 624, in upload_fileobj
    raise ValueError('Fileobj must implement read')
ValueError: Fileobj must implement read
[2024-09-24T17:41:20.394+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_forest_classifier_dag, task_id=get_data, run_id=manual__2024-09-24T17:41:15.640038+00:00, execution_date=20240924T174115, start_date=20240924T174119, end_date=20240924T174120
[2024-09-24T17:41:20.407+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-09-24T17:41:20.408+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-09-24T17:41:20.408+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-24T17:41:20.414+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-09-24T17:41:20.415+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-09-24T17:41:20.416+0000] {taskinstance.py:879} ERROR - Failed to send email to: alexvlg34@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow/dags/.ipynb_checkpoints/hw1-checkpoint.py", line 101, in get_data
    s3_save_file(kwargs['model_name'], 'dataset', data)
  File "/opt/airflow/dags/airflow/dags/.ipynb_checkpoints/hw1-checkpoint.py", line 72, in s3_save_file
    s3_hook.load_file_obj(file_obj=buffer.getvalue(), key=f"AlexTrigolos/{model_name}/datasets/{file_name}.pkl", bucket_name=BUCKET, replace=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1234, in load_file_obj
    self._upload_file_obj(file_obj, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1255, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/s3/inject.py", line 624, in upload_fileobj
    raise ValueError('Fileobj must implement read')
ValueError: Fileobj must implement read

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-09-24T17:41:20.427+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 372 for task get_data (Fileobj must implement read; 28555)
[2024-09-24T17:41:20.460+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-24T17:41:20.469+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
