[2024-10-04T11:41:23.879+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T11:41:23.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Alex_Trigolos.task_init manual__2024-10-04T11:41:21.044700+00:00 [queued]>
[2024-10-04T11:41:23.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Alex_Trigolos.task_init manual__2024-10-04T11:41:21.044700+00:00 [queued]>
[2024-10-04T11:41:23.913+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-04T11:41:23.926+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_init> on 2024-10-04 11:41:21.044700+00:00
[2024-10-04T11:41:23.935+0000] {standard_task_runner.py:64} INFO - Started process 44333 to run task
[2024-10-04T11:41:23.937+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Alex_Trigolos', 'task_init', 'manual__2024-10-04T11:41:21.044700+00:00', '--job-id', '789', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/project-checkpoint.py', '--cfg-path', '/tmp/tmp6az68us9']
[2024-10-04T11:41:23.939+0000] {standard_task_runner.py:91} INFO - Job 789: Subtask task_init
[2024-10-04T11:41:23.979+0000] {task_command.py:426} INFO - Running <TaskInstance: Alex_Trigolos.task_init manual__2024-10-04T11:41:21.044700+00:00 [running]> on host 4b5f1410d111
[2024-10-04T11:41:24.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='Alex_Trigolos' AIRFLOW_CTX_TASK_ID='task_init' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T11:41:21.044700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T11:41:21.044700+00:00'
[2024-10-04T11:41:24.118+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T11:41:24.136+0000] {project-checkpoint.py:98} INFO - Train pipeline started.
[2024-10-04T11:41:24.265+0000] {logging_mixin.py:188} WARNING - 2024/10/04 11:41:24 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-04T11:41:24.332+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T11:41:24.333+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T11:41:24.342+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Alex_Trigolos, task_id=task_init, run_id=manual__2024-10-04T11:41:21.044700+00:00, execution_date=20241004T114121, start_date=20241004T114123, end_date=20241004T114124
[2024-10-04T11:41:24.395+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T11:41:24.434+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T11:41:24.436+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
